load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["something.go"],
    importpath = "github.com/scele/go-dep-bazel-vscode-example/pkg/something",
    visibility = ["//visibility:public"],
)
